[package]

name = "lithos"
description = "A containerization framework for linux"
license = "MIT"
readme = "README.rst"
keywords = ["linux", "namespaces", "containers"]
homepage = "http://github.com/tailhook/lithos"
version = "0.1.0"
authors = ["paul@colomiets.name"]
links = "container"
build = "build.rs"

[dependencies]
regex = "*"
rustc-serialize = "*"
libc = "*"
shaman = "*"
rand = "*"

[dependencies.log]
git = "git://github.com/rust-lang/log"

[dependencies.env_logger]
git = "git://github.com/rust-lang/log"

[dependencies.argparse]
path = 'rust-argparse'

[dependencies.quire]
path = 'rust-quire'

[dependencies.nix]
git = 'https://github.com/carllerche/nix-rust'
